apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
   - name: loki-insecure
     type: "loki"
     url: http://clouder:3100/loki/api/v1/push
  pipelines:
   - name: application-logs
     inputRefs:
     - application
     - audit
     outputRefs:
     - loki-insecure
